apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: API_ENDPOINT
          value: "http://k8s.local/api"    # (placeholder, backend comes later)
